# NumPy Advanced Classwork

Classwork and practice completed during Python and AI/ML training.


In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(f"concat{np.concatenate([a,b])}")
print(f"stack:{np.stack([a,b])}")


concat[1 2 3 4 5 6]
stack:[[1 2 3]
 [4 5 6]]


In [3]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(f"vertical stack{np.vstack([x,y])}")
print(f"hor stack{np.hstack([x,y])}")

vertical stack[[1 2]
 [3 4]
 [5 6]
 [7 8]]
hor stack[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
n=np.arange(1,10)
#even
print(f'split using split:{np.split(n,2)}')
print(f'split using array_split:{np.array_split(n,3)}')
#odd

split using array_split:[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [19]:
rng=np.random.default_rng(42)
print(f"random number:{rng.integers(1,10,size=10)}")
print(f"random floats:{rng.random(5)}")
print(f"{rng.normal(loc=0,scale=1,size=5)}")


random number:[1 7 6 4 4 8 1 7 2 1]
random floats:[0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
[0.87939797 0.77779194 0.0660307  1.12724121 0.46750934]


In [ ]:
x=rng.random((2,2,3))
print(x,x.shape)
x=rng.random((2,3))
print(x,x.shape)

[[[0.66981399 0.43715192 0.8326782 ]
  [0.7002651  0.31236664 0.8322598 ]]

 [[0.80476436 0.38747838 0.2883281 ]
  [0.6824955  0.13975248 0.1999082 ]]] (2, 2, 3)
[[0.00736227 0.78692438 0.66485086]
 [0.70516538 0.78072903 0.45891578]] (2, 3)


In [ ]:
s=np.array(["a",'b','c','d','e'])
print(f"one student{rng.choice(s)}")
print(f"multiple{rng.choice(s,size=3,replace=True)}")

one studentc
multiple['d' 'd' 'c']


In [32]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4,5])
print(f"intersection {np.intersect1d(a,b)}")
print(f"union {np.union1d(a,b)}")
print(f"setdiff {np.setdiff1d(a,b)}")
print(f"superset{np.all(np.isin(a,b))}")

intersection [1 2 3 4]
union [1 2 3 4 5]
setdiff []
supersetTrue


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[3,2,1],[6,5,4],[9,8,7]])
#element wise
print(a*b)
#matrix
print(a@b)
#dot 
print(np.dot(a,b))

[[ 3  4  3]
 [24 25 24]
 [63 64 63]]
[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]
[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]


In [39]:
a=np.array([[1,2],[4,5]],dtype=float)
print(f"deternminant {np.linalg.det(a)}")
print(f"inverse {np.linalg.inv(a)}")
print(f"inverse {a@np.linalg.inv(a)}")


deternminant -2.9999999999999996
inverse [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
inverse [[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [38]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 7],
              [7, 8, 10]], dtype=float)

print(f"determinant: {np.linalg.det(a)}")

inverse = np.linalg.inv(a)
print(f"inverse:\n{inverse}")
print(f"a @ inverse:\n{a @ inverse}")

determinant: 2.9999999999999996
inverse:
[[-2.          1.33333333 -0.33333333]
 [ 3.         -3.66666667  1.66666667]
 [-1.          2.         -1.        ]]
a @ inverse:
[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [-1.33226763e-15  1.00000000e+00 -1.11022302e-16]
 [-8.88178420e-16  0.00000000e+00  1.00000000e+00]]
