# NumPy Basics Classwork

Classwork and practice completed during Python and AI/ML training.


In [2]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.5.3


In [4]:
import numpy as np
a=np.array([1, 2, 3])
print(a)
b=np.array([[4, 5, 6],[7,8,9]])
print(b)
c=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)
print(f'{a.ndim} {b.ndim} {c.ndim}')
print(f'shape:{c.shape} size:{c.size} dtype:{c.dtype} itemsize:{c.itemsize} nbytes:{c.nbytes}')

[1 2 3]
[[4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1 2 3
shape:(2, 2, 2) size:8 dtype:int64 itemsize:8 nbytes:64


In [9]:
print(f"zeros: {np.zeros((2,3))}")
print(f"ones: {np.ones((2,3))}")
print(f"full: {np.full((2,3),7)}")
print(f"Arrange: {np.arange(0,10,2)}")
print(f"Linspace: {np.linspace(0,1,5)}")


zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]
full: [[7 7 7]
 [7 7 7]]
Arrange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
a=np.array([1,2,3,4,5],dtype=np.int32)
b=np.array([1.5,2.5,3.5],dtype=np.float32)
c=np.array([True,False,True])
print(f"a dtype: {a.dtype} b dtype: {b.dtype} c dtype: {c.dtype}")
x=a.astype(np.float64)
print(x,x.dtype)
print(f"first element of a:{a[0]} using idexing")

a dtype: int32 b dtype: float32 c dtype: bool
[1. 2. 3. 4. 5.] float64
first element of a:1 using idexing


In [20]:
matrix=np.array([[1,2,3],
                 [4,5,6]])
print(f"first element of matrix:{matrix[0,0]} using indexing row num and column num")

first element of matrix:1 using indexing row num and column num


In [26]:
#for 1-D
print(a[:1])
print(a[-1])
print(a[::-1])
# for 2D
print(matrix[1,:])

[1]
5
[5 4 3 2 1]
[4 5 6]


In [29]:
arr=np.arange(1,13)
print(arr)
m=arr.reshape(3,4)
print(m)
cube=arr.reshape(2,2,3)
print(cube)
print(cube.shape)
at=arr.reshape(3,-1)
print(at)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#copy-immutable[flatten2dto1d] view-mutable[ravel-2dto1d]
n=np.arange(1,6)
v=n[:]
print(n)
v[0]=10
print(n)
t=np.arange(1,6)
print(t)
copy=t.copy()
copy[0]=10
print(t)


[1 2 3 4 5]
[10  2  3  4  5]
[1 2 3 4 5]
[1 2 3 4 5]


In [32]:
# flatten changes not happen
print(matrix)
flat=matrix.flatten()
flat[0]=90
print(matrix)
#ravel 2d to 1d affected
print(matrix)
rav=matrix.ravel()
rav[0]=90
print(matrix)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[90  2  3]
 [ 4  5  6]]


In [40]:
print(matrix)
print(f"Trandeposed {matrix.T} \nshape:{matrix.T.shape}")

[[90  2  3]
 [ 4  5  6]]
Trandeposed [[90  4]
 [ 2  5]
 [ 3  6]] 
shape:(3, 2)


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(f"vectorised{a+b}")
print(f"vectorised{a-b}")
print(f"vectorised{a*b}")
#scaler oper
print(a)
print(a+5)
print(a-5)
print(a*5)


vectorised[ 6  8 10 12]
vectorised[-4 -4 -4 -4]
vectorised[ 5 12 21 32]
[1 2 3 4]
[6 7 8 9]
[-4 -3 -2 -1]
[ 5 10 15 20]


In [50]:
# adding diff dimension arrays
tuk=np.array([1,2,3])
print(matrix + tuk)

[[91  4  6]
 [ 5  7  9]]


In [53]:
b=np.array([[4, 5, 6],[7,8,9]])
print(b)
c=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [63]:
print(f"sqrt:{np.sqrt(a)}")
print(f"exp:{np.exp(a)}")
print(f"abs:{np.abs(np.array([-2,-3,2]))}")
print(f"log:{np.log(np.array([1,np.e,np.e**2]))}")
print(f"floor:{np.floor(np.array([1.2,3.4]))}")
print(f"floor:{np.ceil(np.array([1.2,3.4]))}")


sqrt:[1.         1.41421356 1.73205081 2.        ]
exp:[ 2.71828183  7.3890561  20.08553692 54.59815003]
abs:[2 3 2]
log:[0. 1. 2.]
floor:[1. 3.]
floor:[2. 4.]


In [66]:
scores = np.array([10,20,30,40,50])
print(f"sum:{np.sum(scores)}")
print(f"mean:{np.mean(scores)}")
print(f"median:{np.median(scores)}")
print(f"max:{np.max(scores)}")
print(f"sum:{np.min(scores)}")

sum:150
mean:30.0
median:30.0
max:50
sum:10


In [68]:
classa=[48,49,50,51,52]
classb=[20,35,50,65,80]
print(f"mean:{np.mean(classa)}")
print(f"mean:{np.mean(classb)}")
print(f"variance:{np.var(classa)}")
print(f"var:{np.var(classb)}")
print(f"stddev:{np.std(classa)}")
print(f"stddev:{np.std(classb)}")

mean:50.0
mean:50.0
variance:2.0
var:450.0
stddev:1.4142135623730951
stddev:21.213203435596427


In [71]:
print(matrix)
print(np.sum(matrix,axis=0))
print(np.sum(matrix,axis=1))

[[90  2  3]
 [ 4  5  6]]
[94  7  9]
[95 15]


In [ ]:
print(arr>20)
print(arr==30)
print(arr!=10)
print(arr<=25)
print(arr)
np.sort(arr)

[False False False False False False False False False False False False]
[False False False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True False  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [74]:
print(np.argsort(arr))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.unique(arr))
print(np.where(arr==3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
11
0
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(array([2]),)
